/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.CategoriasJpaController;
import Control.ContratosJpaController;
import Modelo.Categorias;
import Modelo.Contratos;
import Modelo.Empleados;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.Date;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author hacke
 */
public class ContratoForm extends javax.swing.JDialog {

    /**
     * Creates new form EmpleadoForm
     */
    private final ArrayList<JLabel> labels;
    private final ArrayList<JTextField> textfields;
    private EntityManagerFactory conexion;
    ContratosJpaController contratoController;
    CategoriasJpaController categoriaController;
    private int estado;
    private Date fechaHoy;
    
    @SuppressWarnings("OverridableMethodCallInConstructor")
    public ContratoForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        conexion = Persistence.createEntityManagerFactory("PagoDeSueldosUmlPU");
        contratoController = new ContratosJpaController(conexion);
        categoriaController = new CategoriasJpaController(conexion);
        
        fechaHoy = new Date();
        
        labels = new ArrayList<>();
        labels.add(numeroContratoLabel);
        labels.add(categoriaLabel);
        labels.add(puestoDestinoLabel);
        labels.add(sueldoBasicoLabel);
        labels.add(tipoContratoLabel);
        labels.add(fechaDeAltaLabel);
        labels.add(fechaDeBajaLabel);
        
        textfields = new ArrayList<>();
        textfields.add(numeroContrato);
        textfields.add(categoria);
        textfields.add(puestoDestino);
        textfields.add(sueldoBasico);
        textfields.add(tipoContrato);
        textfields.add(fechaDeAlta);
        textfields.add(fechaDeBaja);
        
        initComponents();
        numeroContrato.setText((contratoController.getContratosCount()+1)+"");
        setLocationRelativeTo(null);
    }
    
    public void validaNumeros(java.awt.event.KeyEvent evt){
        char key = evt.getKeyChar();
        int k = Integer.valueOf(key);
        
        if((k < 48 && k != 8)  || k > 57){
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }else if(k == 8)
            evt.consume();
    }
    
    public void borrarCampos(){
        numeroContrato.setText("");
        categoria.setText("");
        puestoDestino.setText("");
        sueldoBasico.setText("");
        tipoContrato.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contratoLabel = new javax.swing.JLabel();
        numeroContrato = new javax.swing.JTextField();
        categoria = new javax.swing.JTextField();
        puestoDestino = new javax.swing.JTextField();
        sueldoBasico = new javax.swing.JTextField();
        tipoContrato = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        numeroContratoLabel = new javax.swing.JLabel();
        categoriaLabel = new javax.swing.JLabel();
        puestoDestinoLabel = new javax.swing.JLabel();
        sueldoBasicoLabel = new javax.swing.JLabel();
        tipoContratoLabel = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        fechaDeAltaLabel = new javax.swing.JLabel();
        fechaDeBajaLabel = new javax.swing.JLabel();
        fechaDeAlta = new javax.swing.JTextField();
        fechaDeBaja = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("EMPLEADO NUEVO");

        contratoLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        contratoLabel.setText("Datos de Contrato");

        numeroContrato.setEditable(false);
        numeroContrato.setDragEnabled(true);

        sueldoBasico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sueldoBasicoActionPerformed(evt);
            }
        });
        sueldoBasico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sueldoBasicoKeyTyped(evt);
            }
        });

        tipoContrato.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tipoContratoKeyTyped(evt);
            }
        });

        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnBorrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBorrar.setText("Borrar Campos");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        numeroContratoLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        numeroContratoLabel.setText("Número de Contrato");

        categoriaLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        categoriaLabel.setText("Categoría");

        puestoDestinoLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        puestoDestinoLabel.setText("Puesto de Destino");

        sueldoBasicoLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        sueldoBasicoLabel.setText("Sueldo básico");

        tipoContratoLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tipoContratoLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tipoContratoLabel.setText("Tipo de Contrato");

        btnEditar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEditar.setText("Editar");

        fechaDeAltaLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fechaDeAltaLabel.setText("Fecha de alta");

        fechaDeBajaLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fechaDeBajaLabel.setText("Fecha de baja");

        fechaDeAlta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fechaDeAltaKeyTyped(evt);
            }
        });

        fechaDeBaja.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fechaDeBajaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnGuardar)
                            .addGap(167, 167, 167))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEditar)
                            .addGap(18, 18, 18)
                            .addComponent(btnBorrar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sueldoBasicoLabel)
                            .addComponent(numeroContratoLabel)
                            .addComponent(categoriaLabel)
                            .addComponent(puestoDestinoLabel)
                            .addComponent(tipoContratoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fechaDeAltaLabel)
                            .addComponent(fechaDeBajaLabel))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(numeroContrato, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                    .addComponent(categoria)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(puestoDestino, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                    .addComponent(sueldoBasico)
                                    .addComponent(tipoContrato)
                                    .addComponent(fechaDeAlta, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fechaDeBaja, javax.swing.GroupLayout.Alignment.LEADING)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(contratoLabel)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(contratoLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numeroContratoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoriaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(puestoDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(puestoDestinoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sueldoBasico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sueldoBasicoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipoContratoLabel))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaDeAltaLabel)
                    .addComponent(fechaDeAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fechaDeBajaLabel)
                    .addComponent(fechaDeBaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnBorrar)
                    .addComponent(btnEditar))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        estado = 1;
        Empleados empleado = new Empleados();
        
        Categorias nuevaCategoria = new Categorias(categoriaController.getCategoriasCount()+1, 
                categoria.getText(), Double.parseDouble(sueldoBasico.getText()), 
                puestoDestino.getText(), fechaHoy.toString(), estado);
        Contratos nuevoContrato = new Contratos(contratoController.getContratosCount()+1, 
                tipoContrato.getText(), fechaDeAlta.getText(), fechaDeBaja.getText(), 
                fechaHoy.toString(), estado);
        nuevoContrato.setIdempleado(empleado);
        
        categoriaController.create(nuevaCategoria);
        contratoController.create(nuevoContrato);
        JOptionPane.showMessageDialog(null, "CONTRATO CREADO");
        borrarCampos();
        conexion.close();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void sueldoBasicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sueldoBasicoActionPerformed
        
    }//GEN-LAST:event_sueldoBasicoActionPerformed

    private void sueldoBasicoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sueldoBasicoKeyTyped
        validaNumeros(evt);
    }//GEN-LAST:event_sueldoBasicoKeyTyped

    private void tipoContratoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tipoContratoKeyTyped
        
    }//GEN-LAST:event_tipoContratoKeyTyped

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        borrarCampos();
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void fechaDeAltaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fechaDeAltaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaDeAltaKeyTyped

    private void fechaDeBajaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fechaDeBajaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaDeBajaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContratoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContratoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContratoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContratoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ContratoForm dialog = new ContratoForm(new javax.swing.JFrame(), true);
                
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JTextField categoria;
    private javax.swing.JLabel categoriaLabel;
    private javax.swing.JLabel contratoLabel;
    private javax.swing.JTextField fechaDeAlta;
    private javax.swing.JLabel fechaDeAltaLabel;
    private javax.swing.JTextField fechaDeBaja;
    private javax.swing.JLabel fechaDeBajaLabel;
    private javax.swing.JTextField numeroContrato;
    private javax.swing.JLabel numeroContratoLabel;
    private javax.swing.JTextField puestoDestino;
    private javax.swing.JLabel puestoDestinoLabel;
    private javax.swing.JTextField sueldoBasico;
    private javax.swing.JLabel sueldoBasicoLabel;
    private javax.swing.JTextField tipoContrato;
    private javax.swing.JLabel tipoContratoLabel;
    // End of variables declaration//GEN-END:variables
}
